name: Release

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'aws-lambda-sequelize/yarn.lock'
      - uses: actions/cache@v3
        with:
          path: |
            aws-lambda-sequelize/node_modules
          key: ${{ runner.os }}-release-${{ hashFiles('aws-lambda-sequelize/yarn.lock') }}
          restore-keys: ${{ runner.os }}-release-

      - name: Bundle
        run: |
          cd aws-lambda-sequelize
          yarn
          yarn build
      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575
        uses: svenstaro/upload-release-action@2.3.0
        with:
          file: 'aws-lambda-sequelize/dist/index.zip'
